name = "mcp"
main = "src/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

account_id = "2b2a1d3effa7f7fe4fe2a8c4e48681e3"

[vars]
MCPHUB_BACKEND_URL = "http://pixeliumperfecto.co.uk:3001"
ALLOWED_ORIGINS = "*"