name = "mcp"
main = "src/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "mcp"
route = { pattern = "mcp.pixeliumperfecto.co.uk/*", zone_name = "pixeliumperfecto.co.uk" }

[env.development]
name = "mcp-dev"

# Environment variables for the worker
[vars]
MCPHUB_BACKEND_URL = "http://localhost:3000"
ALLOWED_ORIGINS = "https://pixeliumperfecto.co.uk,https://www.pixeliumperfecto.co.uk,http://localhost:3000"

# Build configuration
[build]
command = ""

