name = "mcp"
main = "src/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "mcp"
# route = { pattern = "mcp.pixeliumperfecto.com/*", zone_name = "pixeliumperfecto.com" }

[env.development]
name = "mcp-dev"

# Environment variables for the worker
[env.production.vars]
MCPHUB_BACKEND_URL = "http://localhost:3000"
ALLOWED_ORIGINS = "https://pixeliumperfecto.com,https://www.pixeliumperfecto.com"

[vars]
MCPHUB_BACKEND_URL = "http://localhost:3000"
ALLOWED_ORIGINS = "https://pixeliumperfecto.com,https://www.pixeliumperfecto.com"

# Build configuration
[build]
command = ""
